---
title: "Quantification of Neighborhood-Level Social Determinants of Health in the Continental United States"
collection: publications
permalink: /publication/2020_USSDOH
excerpt: 'How do social determinants of health vary across multiple dimensions and geographic space?. The use of multidimensional geospatial approaches to quantify social determinants of health rather than the use of a singular deprivation index may better capture the complexity and spatial heterogeneity underlying these determinants.'
date: 2020-01-29
venue: 'Jama Network Open'
citation: 'Kolak, M., Bhatt, J., Park, Y. H., Padrón, N. A., & Molefe, A. (2020). Quantification of neighborhood-level social determinants of health in the continental United States. JAMA network open, 3(1), e1919928-e1919928.'
paperurl: 'https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2759757'
---
An association between social and neighborhood characteristics and health outcomes has been reported but remains poorly understood owing to complex multidimensional factors that vary across geographic space.

To quantify social determinants of health (SDOH) as multiple dimensions across the continental United States (the 48 contiguous states and the District of Columbia) at a small-area resolution and to examine the association of SDOH with premature mortality within Chicago, Illinois.

In this cross-sectional study, census tracts from the US Census Bureau from 2014 were used to develop multidimensional SDOH indices and a regional typology of the continental United States at a small-area level (n = 71 901 census tracts with approximately 312 million persons) using dimension reduction and clustering machine learning techniques (unsupervised algorithms used to reduce dimensions of multivariate data). The SDOH indices were used to estimate age-adjusted mortality rates in Chicago (n = 789 census tracts with approximately 7.5 million persons) with a spatial regression for the same period, while controlling for violent crime.

Fifteen variables, measured as a 5-year mean, were selected to characterize SDOH as small-area variations for demographic characteristics of vulnerable groups, economic status, social and neighborhood characteristics, and housing and transportation availability at the census-tract level. This SDOH data matrix was reduced to 4 indices reflecting advantage, isolation, opportunity, and mixed immigrant cohesion and accessibility, which were then clustered into 7 distinct multidimensional neighborhood typologies. The association between SDOH indices and premature mortality (defined as death before age 75 years) in Chicago was measured by years of potential life lost and aggregated to a 5-year mean. Data analyses were conducted between July 1, 2018, and August 30, 2019.

Among the 71 901 census tracts examined across the continental United States, a median (interquartile range) of 27.2% (47.1%) of residents had minority status, 12.1% (7.5%) had disabilities, 22.9% (7.6%) were 18 years and younger, and 13.6% (8.1%) were 65 years and older. Among the 789 census tracts examined in Chicago, a median (interquartile range) of 80.4% (56.3%) of residents had minority status, 10.2% (8.2%) had disabilities, 23.2% (10.9%) were 18 years and younger, and 9.5% (7.1%) were 65 years and older. Four SDOH indices accounted for 71% of the variance across all census tracts in the continental United States in 2014. The SDOH neighborhood typology of extreme poverty, which is of greatest concern to health care practitioners and policy advocates, comprised only 9.6% of all census tracts across the continental United States but characterized small areas of known public health crises. An association was observed between all SDOH indices and age-adjusted premature mortality rates in Chicago (R2 = 0.63; P < .001), even after accounting for violent crime and spatial structures.

The modeling of SDOH as multivariate indices rather than as a singular deprivation index may better capture the complexity and spatial heterogeneity underlying SDOH. During a time of increased attention to SDOH, this analysis may provide actionable information for key stakeholders with respect to the focus of interventions.
